name = "average_azure_fox-2a2c"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "average_azure_fox-2a2c_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "average_azure_fox-2a2c.wasm"
command = "npm run build:release"
